version: "3.9"

services:
  backend:
    build: ./backend
    container_name: support_ticket_system_backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PORT: ${PORT}
    ports:
      - "${PORT}:5000"

  frontend:
    build: ./frontend
    container_name: support_ticket_system_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"